import { createProfitLossSummary } from "@/actions/ledger.actions";
import SubmitButton from "@/components/admin/SubmitButton";
import Link from "next/link";

const input = "w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-800";

export default function NewProfitLossPage() {
  return <div className="mx-auto max-w-4xl"><Link href="/admin/profit-loss" className="text-sm text-gray-500 hover:text-gray-900 dark:text-zinc-400 dark:hover:text-white">Back to Profit & Loss</Link><h1 className="mt-4 text-2xl font-bold text-gray-900 dark:text-white">Create Profit & Loss Summary</h1><p className="mt-2 text-sm text-gray-500 dark:text-zinc-400">Enter the summary values manually for the selected period.</p><form action={createProfitLossSummary} className="mt-6 grid gap-4 rounded-xl border border-gray-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900 md:grid-cols-2"><label className="text-sm font-medium text-gray-700 dark:text-zinc-300">Period<select name="period" className={input}><option value="DAILY">Daily</option><option value="WEEKLY">Weekly</option><option value="MONTHLY">Monthly</option><option value="YEARLY">Yearly</option></select></label><label className="text-sm font-medium text-gray-700 dark:text-zinc-300">Start Date<input name="startDate" required type="date" className={input} /></label><label className="text-sm font-medium text-gray-700 dark:text-zinc-300">End Date<input name="endDate" required type="date" className={input} /></label><label className="text-sm font-medium text-gray-700 dark:text-zinc-300">Sales Amount<input name="salesAmount" type="text" inputMode="numeric" placeholder="Manual sales amount" className={input} /></label><label className="text-sm font-medium text-gray-700 dark:text-zinc-300">Expense Amount<input name="expenseAmount" type="text" inputMode="numeric" placeholder="Manual expense amount" className={input} /></label><label className="text-sm font-medium text-gray-700 dark:text-zinc-300">Profit / Loss<input name="profitLoss" type="text" inputMode="numeric" placeholder="Manual profit / loss" className={input} /></label><label className="md:col-span-2 text-sm font-medium text-gray-700 dark:text-zinc-300">Note<input name="note" placeholder="Note" className={input} /></label><div className="md:col-span-2 flex justify-end"><SubmitButton pendingLabel="Saving..." className="rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-blue-700">Save Summary</SubmitButton></div></form></div>;
}
