import { deleteExpenseStatementEntry } from "@/actions/ledger.actions";
import LedgerDeleteButton from "@/components/admin/LedgerDeleteButton";
import { prisma } from "@/lib/prisma";
import Link from "next/link";
import { Pencil } from "lucide-react";
import { Table } from "../sales/page";

const cols = ["Date", "Product Name", "Cost", "Quantity", "Total Cost", "Deli Charge", "Closing Amount", "Note"];

function parseFilterDate(value?: string) { if (!value || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return undefined; const date = new Date(`${value}T00:00:00`); return Number.isNaN(date.getTime()) ? undefined : date; }

export default async function ExpensesPage({ searchParams }: { searchParams: Promise<{ from?: string; to?: string }> }) {
  const filters = await searchParams;
  const fromDate = parseFilterDate(filters.from);
  const toDate = parseFilterDate(filters.to);
  const entries = await prisma.expenseStatementEntry.findMany({ where: { date: { ...(fromDate ? { gte: fromDate } : {}), ...(toDate ? { lte: new Date(toDate.getTime() + 86_400_000 - 1) } : {}) } }, orderBy: { date: "desc" }, take: 100 });
  const total = entries.reduce((sum, entry) => sum + (entry.closingAmount || 0), 0);
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-bold text-gray-900 dark:text-white">Expense Statement</h1><Link href="/admin/expenses/new" className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-700">Create Expense</Link></div><DateFilter from={filters.from} to={filters.to} /><Table cols={cols} rows={entries.map((x) => [x.date.toLocaleDateString(), x.productName, x.cost, x.quantity, x.totalCost, x.deliCharge, x.closingAmount, x.note])} totalColumnIndex={6} totalValue={total} actions={(index) => <><Link href={`/admin/expenses/${entries[index].id}/edit`} aria-label="Edit entry" title="Edit entry" className="text-amber-600 hover:text-amber-700 dark:text-amber-400"><Pencil className="h-4 w-4" /></Link><LedgerDeleteButton onDelete={deleteExpenseStatementEntry.bind(null, entries[index].id)} /></>} /></div>;
}

function DateFilter({ from, to }: { from?: string; to?: string }) { const today = new Date(`${new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Yangon" }).format(new Date())}T00:00:00`); const format = (date: Date) => date.toISOString().slice(0, 10); const day = new Date(today); const week = new Date(today); week.setDate(week.getDate() - 6); const month = new Date(today); month.setMonth(month.getMonth() - 1); return <form method="get" className="flex flex-wrap items-end gap-3 rounded-xl border border-gray-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"><label className="text-sm font-medium text-gray-700 dark:text-zinc-300">From<input name="from" type="date" defaultValue={from || ""} className="mt-1 block rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-800 dark:text-white" /></label><label className="text-sm font-medium text-gray-700 dark:text-zinc-300">To<input name="to" type="date" defaultValue={to || ""} className="mt-1 block rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-800 dark:text-white" /></label><button type="submit" className="rounded-lg bg-gray-900 px-4 py-2 text-sm font-semibold text-white hover:bg-gray-700 dark:bg-white dark:text-gray-900">Filter</button><Link href={`/admin/expenses?from=${format(day)}&to=${format(today)}`} className="rounded-lg border border-gray-300 px-3 py-2 text-sm font-medium hover:bg-gray-50 dark:border-zinc-700 dark:hover:bg-zinc-800">1 Day</Link><Link href={`/admin/expenses?from=${format(week)}&to=${format(today)}`} className="rounded-lg border border-gray-300 px-3 py-2 text-sm font-medium hover:bg-gray-50 dark:border-zinc-700 dark:hover:bg-zinc-800">1 Week</Link><Link href={`/admin/expenses?from=${format(month)}&to=${format(today)}`} className="rounded-lg border border-gray-300 px-3 py-2 text-sm font-medium hover:bg-gray-50 dark:border-zinc-700 dark:hover:bg-zinc-800">1 Month</Link><Link href="/admin/expenses" className="rounded-lg border border-gray-300 px-3 py-2 text-sm font-medium text-gray-500 hover:bg-gray-50 hover:text-gray-900 dark:border-zinc-700 dark:text-zinc-400 dark:hover:bg-zinc-800 dark:hover:text-white">Clear Filter</Link></form>; }
