import { createManualOrder } from "@/actions/order.actions";
import AttachmentUploadField from "@/components/admin/AttachmentUploadField";

const input = "mt-1 w-full rounded-lg border border-gray-300 bg-white px-3 py-2.5 text-sm text-gray-900 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white";

export default function NewManualOrderPage() {
  return <div className="mx-auto max-w-4xl"><h1 className="text-2xl font-bold text-gray-900 dark:text-white">Create Manual Order</h1><p className="mt-2 text-sm text-gray-500 dark:text-zinc-400">Enter customer and delivery details without changing storefront inventory.</p><form action={createManualOrder} className="mt-6 grid gap-5 rounded-xl border border-gray-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900 md:grid-cols-2"><Field label="Customer Name" name="customerName" required /><Field label="Account / Channel" name="customerAccount" placeholder="Facebook, Telegram..." /><Field label="Phone Number" name="customerPhone" /><Field label="Delivery Date" name="deliveryDate" type="date" /><div className="md:col-span-2"><Field label="Delivery Address" name="deliveryAddress" /></div><Field label="Item Name" name="itemName" required /><Field label="Leather" name="leather" /><div className="md:col-span-2"><label className="block text-sm font-medium text-gray-700 dark:text-zinc-300">Description<textarea name="description" rows={3} className={input} /></label></div><Field label="Price (Ks)" name="price" type="number" required min="1" /><Field label="Quantity" name="quantity" type="number" required min="1" /><Field label="Deposit (Ks)" name="deposit" type="number" min="0" /><Field label="Deli Charge (Ks)" name="deliveryCharge" type="number" min="0" /><div className="md:col-span-2"><Field label="Total Amount (Ks)" name="totalAmount" type="number" required min="0" /></div><div className="md:col-span-2"><label className="block text-sm font-medium text-gray-700 dark:text-zinc-300">Setup Note<textarea name="setupNote" rows={3} className={input} /></label></div><AttachmentUploadField /><div className="md:col-span-2 flex justify-end"><button className="rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-blue-700">Create Order</button></div></form></div>;
}

function Field({ label, name, type = "text", required, placeholder, min }: { label: string; name: string; type?: string; required?: boolean; placeholder?: string; min?: string }) { return <label className="block text-sm font-medium text-gray-700 dark:text-zinc-300">{label}<input name={name} type={type} required={required} placeholder={placeholder} min={min} className={input} /></label>; }
