import { deleteSalesStatementEntry } from "@/actions/ledger.actions";
import LedgerDeleteButton from "@/components/admin/LedgerDeleteButton";
import { prisma } from "@/lib/prisma";
import { Pencil } from "lucide-react";
import Link from "next/link";
import type { ReactNode } from "react";

const cols = ["Date", "Waybill No", "Receiver Name", "Product Name", "To City", "Price", "Prepayment", "Deli Charge", "COD Charge", "COD Amount", "Closing Balance", "Note"];

function parseFilterDate(value?: string) {
  if (!value || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return undefined;
  const date = new Date(`${value}T00:00:00`);
  return Number.isNaN(date.getTime()) ? undefined : date;
}

export default async function SalesPage({ searchParams }: { searchParams: Promise<{ from?: string; to?: string }> }) {
  const filters = await searchParams;
  const fromDate = parseFilterDate(filters.from);
  const toDate = parseFilterDate(filters.to);
  const entries = await prisma.salesStatementEntry.findMany({ where: { date: { ...(fromDate ? { gte: fromDate } : {}), ...(toDate ? { lte: new Date(toDate.getTime() + 86_400_000 - 1) } : {}) } }, orderBy: { date: "desc" }, take: 100 });
  const total = entries.reduce((sum, entry) => sum + (entry.closingBalance || 0), 0);

  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-bold text-gray-900 dark:text-white">Sales Statement</h1><Link href="/admin/sales/new" className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-700">Create Sale</Link></div><DateFilter from={filters.from} to={filters.to} /><Table cols={cols} rows={entries.map((x) => [x.date.toLocaleDateString(), x.waybillNo, x.receiverName, x.productName, x.toCity, x.price, x.prepayment, x.deliCharge, x.codCharge, x.codAmount, x.closingBalance, x.note])} totalColumnIndex={10} totalValue={total} actions={(index) => <><Link href={`/admin/sales/${entries[index].id}/edit`} aria-label="Edit entry" title="Edit entry" className="text-amber-600 hover:text-amber-700 dark:text-amber-400"><Pencil className="h-4 w-4" /></Link><LedgerDeleteButton onDelete={deleteSalesStatementEntry.bind(null, entries[index].id)} /></>} /></div>;
}

function DateFilter({ from, to }: { from?: string; to?: string }) { const today = new Date(`${new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Yangon" }).format(new Date())}T00:00:00`); const format = (date: Date) => date.toISOString().slice(0, 10); const day = new Date(today); const week = new Date(today); week.setDate(week.getDate() - 6); const month = new Date(today); month.setMonth(month.getMonth() - 1); return <form method="get" className="flex flex-wrap items-end gap-3 rounded-xl border border-gray-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"><label className="text-sm font-medium text-gray-700 dark:text-zinc-300">From<input name="from" type="date" defaultValue={from || ""} className="mt-1 block rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-800 dark:text-white" /></label><label className="text-sm font-medium text-gray-700 dark:text-zinc-300">To<input name="to" type="date" defaultValue={to || ""} className="mt-1 block rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-800 dark:text-white" /></label><button type="submit" className="rounded-lg bg-gray-900 px-4 py-2 text-sm font-semibold text-white hover:bg-gray-700 dark:bg-white dark:text-gray-900">Filter</button><Link href={`/admin/sales?from=${format(day)}&to=${format(today)}`} className="rounded-lg border border-gray-300 px-3 py-2 text-sm font-medium hover:bg-gray-50 dark:border-zinc-700 dark:hover:bg-zinc-800">1 Day</Link><Link href={`/admin/sales?from=${format(week)}&to=${format(today)}`} className="rounded-lg border border-gray-300 px-3 py-2 text-sm font-medium hover:bg-gray-50 dark:border-zinc-700 dark:hover:bg-zinc-800">1 Week</Link><Link href={`/admin/sales?from=${format(month)}&to=${format(today)}`} className="rounded-lg border border-gray-300 px-3 py-2 text-sm font-medium hover:bg-gray-50 dark:border-zinc-700 dark:hover:bg-zinc-800">1 Month</Link><Link href="/admin/sales" className="rounded-lg border border-gray-300 px-3 py-2 text-sm font-medium text-gray-500 hover:bg-gray-50 hover:text-gray-900 dark:border-zinc-700 dark:text-zinc-400 dark:hover:bg-zinc-800 dark:hover:text-white">Clear Filter</Link></form>; }

export function Table({ cols, rows, actions, totalColumnIndex, totalValue }: { cols: string[]; rows: (string | number | null)[][]; actions?: (index: number) => ReactNode; totalColumnIndex?: number; totalValue?: number }) { return <div className="overflow-x-auto rounded-xl border border-gray-200 dark:border-zinc-800"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50 dark:bg-zinc-900"><tr>{cols.map((c) => <th key={c} className="whitespace-nowrap px-4 py-3 font-semibold">{c}</th>)}{actions && <th className="whitespace-nowrap px-4 py-3 font-semibold">Action</th>}</tr></thead><tbody>{rows.map((r, i) => <tr key={i} className="border-t border-gray-200 dark:border-zinc-800">{r.map((v, j) => <td key={j} className="max-w-64 whitespace-pre-wrap px-4 py-3">{v ?? "-"}</td>)}{actions && <td className="whitespace-nowrap px-4 py-3"><div className="flex items-center gap-3">{actions(i)}</div></td>}</tr>)}</tbody>{totalColumnIndex !== undefined && <tfoot><tr className="border-t-2 border-gray-300 bg-gray-50 font-bold dark:border-zinc-700 dark:bg-zinc-900">{cols.map((_, j) => <td key={j} className="whitespace-nowrap px-4 py-3">{j === 0 ? "Total" : j === totalColumnIndex ? (totalValue || 0).toLocaleString() : ""}</td>)}{actions && <td />}</tr></tfoot>}</table></div>; }
