import { deleteSalesStatementEntry } from "@/actions/ledger.actions";
import LedgerDeleteButton from "@/components/admin/LedgerDeleteButton";
import { prisma } from "@/lib/prisma";
import Link from "next/link";
import type { ReactNode } from "react";
const cols = ["Date","Waybill No","Receiver Name","Product Name","To City","Price","Prepayment","Deli Charge","COD Charge","COD Amount","Closing Balance"];
export default async function SalesPage() { const entries = await prisma.salesStatementEntry.findMany({ orderBy: { date: "desc" }, take: 100 }); return <LedgerPage title="Sales Statement" cols={cols} rows={entries.map(x => [x.date.toLocaleDateString(),x.waybillNo,x.receiverName,x.productName,x.toCity,x.price,x.prepayment,x.deliCharge,x.codCharge,x.codAmount,x.closingBalance])} actions={(index) => <><Link href={`/admin/sales/${entries[index].id}/edit`} aria-label="Edit entry" className="text-amber-600 hover:text-amber-700 dark:text-amber-400">Edit</Link><LedgerDeleteButton onDelete={deleteSalesStatementEntry.bind(null, entries[index].id)} /></>} />; }
function LedgerPage({title,cols,rows,actions}:{title:string;cols:string[];rows:(string|number|null)[][];actions:(index:number)=>ReactNode}) { return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-bold text-gray-900 dark:text-white">{title}</h1><Link href="/admin/sales/new" className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-700">Create Sale</Link></div><Table cols={cols} rows={rows} actions={actions}/></div>; }
export function Table({cols,rows,actions}:{cols:string[];rows:(string|number|null)[][];actions?: (index:number)=>ReactNode}) { return <div className="overflow-x-auto rounded-xl border border-gray-200 dark:border-zinc-800"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50 dark:bg-zinc-900"><tr>{cols.map(c=><th key={c} className="whitespace-nowrap px-4 py-3 font-semibold">{c}</th>)}{actions && <th className="whitespace-nowrap px-4 py-3 font-semibold">Action</th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t border-gray-200 dark:border-zinc-800">{r.map((v,j)=><td key={j} className="whitespace-nowrap px-4 py-3">{v ?? "-"}</td>)}{actions && <td className="whitespace-nowrap px-4 py-3"><div className="flex items-center gap-3">{actions(i)}</div></td>}</tr>)}</tbody></table></div>; }
